 
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package praktikumpemvis_latihan1;

/**
 *
 * @author firak
 */

public class countdown extends javax.swing.JFrame {
    
    private int sisawaktu = 30; //variabel sisa waktu digunakan untuk menyimpan angka (30 detik)
    private Timer timer; //digunakan untuk mengurangi detik di variabel sisa waktu

    /**
     * Creates new form countdown
     */
    public countdown() { //countdown ini konstruktor 
        initComponents();
        
        tjam.setEditable(false); // Membuat JTextField hanya tampilan
        timer = new Timer(1000, new ActionListener() { 
            @Override
            public void actionPerformed(ActionEvent e) {
                sisawaktu--;
                tjam.setText(String.valueOf(sisawaktu));

                if (sisawaktu == 0) {
                    timer.stop();
                }
            }
        });
    }
                

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tjam = new javax.swing.JTextField();
        bmulai = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Menuju Berbuka Puasa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 140, 190, 32);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("17:32 WIB");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 170, 86, 18);

        jLabel3.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("- HAPPY IFTAR -");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 340, 117, 18);

        tjam.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        tjam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tjam.setText("30 Detik");
        tjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tjamActionPerformed(evt);
            }
        });
        getContentPane().add(tjam);
        tjam.setBounds(40, 200, 210, 80);

        bmulai.setText("Start");
        bmulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmulaiActionPerformed(evt);
            }
        });
        getContentPane().add(bmulai);
        bmulai.setBounds(200, 290, 70, 23);

        bkeluar.setText("Exit");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bkeluar);
        bkeluar.setBounds(10, 430, 75, 23);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("1 Menit");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 120, 70, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\firak\\OneDrive\\Pictures\\download (2).jpeg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 280, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bmulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmulaiActionPerformed
        // TODO add your handling code here:
        timer.start(); //untuk memulai timer
    }//GEN-LAST:event_bmulaiActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0); //program akan tertutup ketika button exit di klik
        
    }//GEN-LAST:event_bkeluarActionPerformed

    private void tjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tjamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(countdown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(countdown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(countdown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(countdown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new countdown().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bmulai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tjam;
    // End of variables declaration//GEN-END:variables
}
