/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project1_pemvis;

import javax.swing.JOptionPane; 

/**
 *
 * @author firak
 */
public class tugas_form1 extends javax.swing.JFrame {

    public tugas_form1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jeniskelamin = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        tnim = new javax.swing.JTextField();
        tprodi = new javax.swing.JTextField();
        tfakultas = new javax.swing.JTextField();
        talamat = new javax.swing.JTextField();
        tnotelepon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        teksarea = new javax.swing.JTextArea();
        button1 = new javax.swing.JRadioButton();
        button2 = new javax.swing.JRadioButton();
        bexit = new javax.swing.JButton();
        breset = new javax.swing.JButton();
        bsimpan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORMULIR PENDAFTARAN UKM-FT TOFATEK");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 10, 310, 16);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UNIVERSITAS TRUNOJOYO MADURA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 30, 260, 20);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NAMA LENGKAP");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(6, 79, 130, 16);

        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("NIM");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(6, 110, 142, 16);

        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("PROGRAM STUDI");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(6, 144, 111, 16);

        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setText("FAKULTAS");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(6, 178, 111, 16);

        jLabel10.setForeground(new java.awt.Color(242, 242, 242));
        jLabel10.setText("ALAMAT");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(6, 212, 100, 16);

        jLabel11.setForeground(new java.awt.Color(242, 242, 242));
        jLabel11.setText("NOMOR TELEPON");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(6, 246, 111, 16);

        jLabel12.setForeground(new java.awt.Color(242, 242, 242));
        jLabel12.setText("JENIS KELAMIN");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(6, 279, 111, 16);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(6, 439, 0, 0);

        tnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnamaActionPerformed(evt);
            }
        });
        getContentPane().add(tnama);
        tnama.setBounds(172, 76, 211, 22);
        getContentPane().add(tnim);
        tnim.setBounds(172, 107, 211, 22);
        getContentPane().add(tprodi);
        tprodi.setBounds(172, 141, 211, 22);
        getContentPane().add(tfakultas);
        tfakultas.setBounds(172, 175, 211, 22);
        getContentPane().add(talamat);
        talamat.setBounds(172, 209, 211, 22);
        getContentPane().add(tnotelepon);
        tnotelepon.setBounds(172, 243, 211, 22);

        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("ALASAN MASUK TOFATEK:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(6, 309, 190, 16);

        teksarea.setColumns(20);
        teksarea.setRows(5);
        jScrollPane1.setViewportView(teksarea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(6, 331, 340, 110);

        jeniskelamin.add(button1);
        button1.setText("PEREMPUAN");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(170, 280, 110, 21);

        jeniskelamin.add(button2);
        button2.setText("LAKI-LAKI");
        getContentPane().add(button2);
        button2.setBounds(290, 280, 90, 21);

        bexit.setText("EXIT");
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });
        getContentPane().add(bexit);
        bexit.setBounds(370, 440, 72, 23);

        breset.setText("RESET");
        breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresetActionPerformed(evt);
            }
        });
        getContentPane().add(breset);
        breset.setBounds(370, 410, 72, 23);

        bsimpan.setText("SAVE");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(bsimpan);
        bsimpan.setBounds(370, 380, 72, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1_pemvis/ID Card peserta opsi2.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-3, 0, 460, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here:
        String nama  = tnama.getText();
        String nim = tnim.getText();
        String prodi = tprodi.getText();
        String fakultas = tfakultas.getText();
        String alamat = talamat.getText();
        String notelepon = tnotelepon.getText();
        String jenisKelamin = "";
        if (button1.isSelected()) {
            jenisKelamin = "Perempuan";
        } else if (button2.isSelected()) {
            jenisKelamin = "Laki-Laki";
        }
        
        String alasan = teksarea.getText();
        
        JOptionPane.showMessageDialog(null, "Nama: "+ nama + "\n Nim: "+ nim + "\n Prodi: "+ prodi + 
                "\n Fakultas: "+ fakultas + "\n Alamat: "+ alamat + "\n No Telepon: "+ notelepon + "\n Jenis Kelamin: "+ 
                jenisKelamin + "\n Alasan ingin bergabung: "+ alasan );                                        
    }//GEN-LAST:event_bsimpanActionPerformed

    private void tnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnamaActionPerformed

    private void bresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresetActionPerformed
        // TODO add your handling code here:
        tnama.setText("");
        tnim.setText("");
        tprodi.setText("");
        tfakultas.setText("");
        talamat.setText("");
        tnotelepon.setText("");
        jeniskelamin.clearSelection();
        teksarea.setText("");
    }//GEN-LAST:event_bresetActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tugas_form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tugas_form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tugas_form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tugas_form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tugas_form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bexit;
    private javax.swing.JButton breset;
    private javax.swing.JButton bsimpan;
    private javax.swing.JRadioButton button1;
    private javax.swing.JRadioButton button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup jeniskelamin;
    private javax.swing.JTextField talamat;
    private javax.swing.JTextArea teksarea;
    private javax.swing.JTextField tfakultas;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tnim;
    private javax.swing.JTextField tnotelepon;
    private javax.swing.JTextField tprodi;
    // End of variables declaration//GEN-END:variables
}
